services:
  - type: web
    name: fastapi-app
    runtime: python
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: UVICORN_CMD
        value: uvicorn main:app --host 0.0.0.0 --port 10000
